---
# NetworkPolicy for Platform UI ingress traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: platform-ui-ingress
  namespace: platform-system
  labels:
    app: platform-ui
    platform.io/component: "platform-ui"
    version: v1.1.0
  annotations:
    platform.io/description: "NetworkPolicy for Platform UI ingress traffic control"
spec:
  podSelector:
    matchLabels:
      app: platform-ui
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from Istio ingress gateway
    - from:
        - namespaceSelector:
            matchLabels:
              name: istio-system
        - podSelector:
            matchLabels:
              app: istio-proxy
    # Allow traffic from Istio sidecar proxies
    - from:
        - namespaceSelector:
            matchLabels:
              name: istio-system
      ports:
        - protocol: TCP
          port: 15000
        - protocol: TCP
          port: 15001
        - protocol: TCP
          port: 15006
        - protocol: TCP
          port: 15020
    # Allow traffic from monitoring systems
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
    - from:
        - namespaceSelector:
            matchLabels:
              name: prometheus
    # Allow traffic from same namespace (platform-system)
    - from:
        - namespaceSelector:
            matchLabels:
              name: platform-system
    # Allow health checks from load balancers and ingress controllers
    - ports:
        - protocol: TCP
          port: 3000
      from: [] # Allow from anywhere for health checks
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow HTTPS to external services (Microsoft login, CDNs, etc.)
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # Allow HTTP to platform-api and internal services
    - to:
        - namespaceSelector:
            matchLabels:
              name: platform-system
        - podSelector:
            matchLabels:
              app: platform-api
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 3000
    # Allow WebSocket connections to platform-api
    - to:
        - namespaceSelector:
            matchLabels:
              name: platform-system
        - podSelector:
            matchLabels:
              app: platform-api
      ports:
        - protocol: TCP
          port: 8080
    # Allow access to Kubernetes API server (for client-side operations)
    - to: []
      ports:
        - protocol: TCP
          port: 6443
        - protocol: TCP
          port: 443
    # Allow Istio sidecar communication
    - to:
        - namespaceSelector:
            matchLabels:
              name: istio-system
      ports:
        - protocol: TCP
          port: 15000
        - protocol: TCP
          port: 15001
        - protocol: TCP
          port: 15004
        - protocol: TCP
          port: 15006
        - protocol: TCP
          port: 15010
        - protocol: TCP
          port: 15011
        - protocol: TCP
          port: 15014

---
# NetworkPolicy for Platform UI egress traffic (more restrictive, optional)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: platform-ui-egress-strict
  namespace: platform-system
  labels:
    app: platform-ui
    platform.io/component: "platform-ui"
    version: v1.1.0
    policy-type: strict
  annotations:
    platform.io/description: "Strict NetworkPolicy for Platform UI egress traffic (optional, can be enabled for enhanced security)"
spec:
  podSelector:
    matchLabels:
      app: platform-ui
      policy-type: strict # Only apply to pods with this label
  policyTypes:
    - Egress
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow HTTPS to Microsoft authentication endpoints
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # Allow access to platform-api only
    - to:
        - namespaceSelector:
            matchLabels:
              name: platform-system
        - podSelector:
            matchLabels:
              app: platform-api
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 8080
    # Allow Istio sidecar communication
    - to:
        - namespaceSelector:
            matchLabels:
              name: istio-system
      ports:
        - protocol: TCP
          port: 15000
        - protocol: TCP
          port: 15001
        - protocol: TCP
          port: 15004
        - protocol: TCP
          port: 15006
        - protocol: TCP
          port: 15010
        - protocol: TCP
          port: 15011
        - protocol: TCP
          port: 15014
