---
# External Secret for Platform UI
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-ui-secrets
  namespace: platform-system
  labels:
    app: platform-ui
    platform.io/component: "platform-ui"
    version: v1.1.0
  annotations:
    platform.io/description: "External Secret for Platform UI sensitive configuration"
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: platform-ui-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app: platform-ui
          platform.io/component: "platform-ui"
          version: v1.1.0
      data:
        # Azure AD Application Secret (if using client credentials flow)
        azure-client-secret: "{{ .azureClientSecret | toString }}"
        # Session signing key for nginx
        session-secret: "{{ .sessionSecret | toString }}"
        # JWT signing key for client-side token validation
        jwt-public-key: "{{ .jwtPublicKey | toString }}"
        # Application Insights connection string
        appinsights-connection-string: "{{ .appInsightsConnectionString | toString }}"
        # Additional secrets can be added here
  data:
    - secretKey: azureClientSecret
      remoteRef:
        key: platform-ui-azure-client-secret
    - secretKey: sessionSecret
      remoteRef:
        key: platform-ui-session-secret
    - secretKey: jwtPublicKey
      remoteRef:
        key: platform-api-jwt-public-key
    - secretKey: appInsightsConnectionString
      remoteRef:
        key: platform-appinsights-connection-string

---
# Fallback Secret (for development/testing - should be replaced by External Secret in production)
apiVersion: v1
kind: Secret
metadata:
  name: platform-ui-secrets-fallback
  namespace: platform-system
  labels:
    app: platform-ui
    platform.io/component: "platform-ui"
    version: v1.1.0
    fallback: "true"
  annotations:
    platform.io/description: "Fallback Secret for Platform UI (replace with External Secret in production)"
type: Opaque
data:
  # Base64 encoded placeholders - REPLACE THESE IN PRODUCTION
  azure-client-secret: U0VUX1lPVVJfQ0xJRU5UX1NFQ1JFVA== # "SET_YOUR_CLIENT_SECRET"
  session-secret: cGxhdGZvcm0tdWktc2Vzc2lvbi1zZWNyZXQtY2hhbmdlLXRoaXMtaW4tcHJvZHVjdGlvbg== # "platform-ui-session-secret-change-this-in-production"
  jwt-public-key: U0VUX1lPVVJfSldUX1BVQkxJQ19LRVk= # "SET_YOUR_JWT_PUBLIC_KEY"
  appinsights-connection-string: U0VUX1lPVVJfQVBQSU5TSUdIVFNfQ09OTkVDVElPTl9TVFJJTkc= # "SET_YOUR_APPINSIGHTS_CONNECTION_STRING"
