---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-ui
  namespace: platform-system
  labels:
    app: platform-ui
    platform.io/component: "platform-ui"
    version: v1.1.0
    azure.workload.identity/use: "true"
  annotations:
    platform.io/description: "Service account for Platform UI with Azure Workload Identity"
    azure.workload.identity/client-id: "SET_YOUR_UI_CLIENT_ID"
    azure.workload.identity/tenant-id: "SET_YOUR_TENANT_ID"
automountServiceAccountToken: false
