apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-api-config
  namespace: platform-system
  labels:
    app: platform-api
    component: config
data:
  NODE_ENV: "development"
  PORT: "3000"
  KUBE_NAMESPACE: "default"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  PLATFORM_COST_TRACKING: "false"
  DB_SSL: "false"
  RATE_LIMIT_MAX_REQUESTS: "1000"
  RATE_LIMIT_WINDOW_MS: "900000"