apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    name: platform-system
    platform.io/managed: "true"
  annotations:
    platform.io/description: "Platform engineering services namespace"
