apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-api
  namespace: platform-system
  labels:
    app: platform-api
    component: serviceaccount
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-api-cluster-role
  labels:
    app: platform-api
    component: rbac
rules:
- apiGroups: [""]
  resources: ["namespaces", "serviceaccounts", "secrets", "configmaps", "resourcequotas", "limitranges"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-api-cluster-role-binding
  labels:
    app: platform-api
    component: rbac
subjects:
- kind: ServiceAccount
  name: platform-api
  namespace: platform-system
roleRef:
  kind: ClusterRole
  name: platform-api-cluster-role
  apiGroup: rbac.authorization.k8s.io