apiVersion: v1
kind: Service
metadata:
  name: platform-api
  namespace: platform-system
  labels:
    app: platform-api
    component: service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: platform-api
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: platform-api-headless
  namespace: platform-system
  labels:
    app: platform-api
    component: headless-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app: platform-api
    component: api