# Development secrets for local testing and non-production environments
# WARNING: These are sample values only - never use in production!
apiVersion: v1
kind: Secret
metadata:
  name: dev-backend-secrets
  namespace: external-secrets-system
  labels:
    platform.io/environment: "development"
    platform.io/component: "external-secrets"
    platform.io/managed-by: "manual"
    platform.io/secret-type: "development"
  annotations:
    platform.io/description: "Development secrets for testing External Secrets integration"
    platform.io/warning: "DO NOT USE IN PRODUCTION - These are sample values only"
type: Opaque
stringData:
  # Platform API secrets - Development only
  platform-jwt-secret: "dev-jwt-secret-32-chars-minimum-length-required-for-security"
  platform-db-host: "localhost"
  platform-db-port: "5432"
  platform-db-name: "platform_dev"
  platform-db-user: "platform_dev_user"
  platform-db-password: "dev-postgres-password-change-me"
  platform-db-ssl-mode: "disable"
  platform-azure-client-id: "00000000-0000-0000-0000-000000000000"
  platform-azure-client-secret: "dev-client-secret-change-in-production"
  platform-azure-tenant-id: "00000000-0000-0000-0000-000000000000"
  platform-encryption-key: "dev-encryption-key-32-bytes-long-minimum-for-aes-256-security"
  platform-api-key: "dev-api-key-should-be-uuid-or-similar-format"
  platform-webhook-secret: "dev-webhook-secret-for-external-integrations"

  # Redis secrets - Development
  platform-redis-host: "localhost"
  platform-redis-port: "6379"
  platform-redis-password: "dev-redis-password"

  # Cert-manager secrets - Development (self-signed)
  acme-account-private-key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA0Z9VS5JJcds3xfn/ygWyF72uHULn5pVMxmlQnBMVkqWvxmPg
    e3XrGWpxy3Y0VgLqyJhRAl50gazWp1ODLNbCQayS+eEGSbDlJZ3jiHXJjY2VmqJC
    dGDBQ+IXuHM6TvCrwu8TAJ0J1gxLbcBNdUF3qFGCb6qqOCFkmiYlj3L7w4jfQvPR
    XYPPBWpXsvWXyEYcvg9J/0JHdNnoGcsVmqWFLVJpEKLWP7zYlB6rWyNLsFKO5J6L
    dev-key-content-example-only-do-not-use-in-production-environments
    -----END RSA PRIVATE KEY-----
  acme-account-url: "https://acme-staging-v02.api.letsencrypt.org/acme/acct/dev"
  # External DNS secrets - Development
  azure-tenant-id: "00000000-0000-0000-0000-000000000000"
  azure-subscription-id: "00000000-0000-0000-0000-000000000000"
  dns-resource-group: "dev-dns-rg"
  external-dns-client-id: "00000000-0000-0000-0000-000000000000"
  external-dns-client-secret: "dev-external-dns-secret-change-me"

  # Monitoring secrets - Development
  grafana-admin-password: "dev-admin-password"
  prometheus-password: "dev-prometheus-password"
  azure-monitor-client-id: "00000000-0000-0000-0000-000000000000"
  azure-monitor-client-secret: "dev-monitor-secret"

  # Istio TLS secrets - Development (self-signed)
  istio-gateway-tls-cert: |
    -----BEGIN CERTIFICATE-----
    MIIDXTCCAkWgAwIBAgIJAKZpqZ... (truncated for brevity)
    dev-certificate-content-only-for-testing
    -----END CERTIFICATE-----
  istio-gateway-tls-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC...
    dev-private-key-content-only-for-testing
    -----END PRIVATE KEY-----
---
# Development ExternalSecret using local Kubernetes backend
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-api-dev-secrets
  namespace: platform-system
  labels:
    app.kubernetes.io/name: platform-api
    app.kubernetes.io/component: backend
    platform.io/environment: "development"
    platform.io/component: "platform-api"
    platform.io/managed-by: "external-secrets"
    platform.io/secret-type: "application"
  annotations:
    platform.io/description: "Development secrets for Platform API using Kubernetes backend"
    platform.io/warning: "Development environment only"
spec:
  refreshInterval: 30s # Fast refresh for development

  secretStoreRef:
    name: kubernetes-secret-store
    kind: SecretStore

  target:
    name: platform-api-secrets
    creationPolicy: Owner
    deletionPolicy: Delete # Delete secrets in development
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: platform-api
          platform.io/environment: "development"
          platform.io/secret-type: "application"
      data:
        # Map all platform secrets for development
        JWT_SECRET: "{{ .platform_jwt_secret | toString }}"
        AZURE_CLIENT_ID: "{{ .platform_azure_client_id | toString }}"
        AZURE_CLIENT_SECRET: "{{ .platform_azure_client_secret | toString }}"
        AZURE_TENANT_ID: "{{ .platform_azure_tenant_id | toString }}"
        DB_HOST: "{{ .platform_db_host | toString }}"
        DB_PORT: "{{ .platform_db_port | toString }}"
        DB_NAME: "{{ .platform_db_name | toString }}"
        DB_USER: "{{ .platform_db_user | toString }}"
        DB_PASSWORD: "{{ .platform_db_password | toString }}"
        REDIS_HOST: "{{ .platform_redis_host | toString }}"
        REDIS_PORT: "{{ .platform_redis_port | toString }}"
        REDIS_PASSWORD: "{{ .platform_redis_password | toString }}"
        ENCRYPTION_KEY: "{{ .platform_encryption_key | toString }}"
        API_KEY: "{{ .platform_api_key | toString }}"

  data:
    - secretKey: platform_jwt_secret
      remoteRef:
        key: dev-backend-secrets
        property: platform-jwt-secret
    - secretKey: platform_azure_client_id
      remoteRef:
        key: dev-backend-secrets
        property: platform-azure-client-id
    - secretKey: platform_azure_client_secret
      remoteRef:
        key: dev-backend-secrets
        property: platform-azure-client-secret
    - secretKey: platform_azure_tenant_id
      remoteRef:
        key: dev-backend-secrets
        property: platform-azure-tenant-id
    - secretKey: platform_db_host
      remoteRef:
        key: dev-backend-secrets
        property: platform-db-host
    - secretKey: platform_db_port
      remoteRef:
        key: dev-backend-secrets
        property: platform-db-port
    - secretKey: platform_db_name
      remoteRef:
        key: dev-backend-secrets
        property: platform-db-name
    - secretKey: platform_db_user
      remoteRef:
        key: dev-backend-secrets
        property: platform-db-user
    - secretKey: platform_db_password
      remoteRef:
        key: dev-backend-secrets
        property: platform-db-password
    - secretKey: platform_redis_host
      remoteRef:
        key: dev-backend-secrets
        property: platform-redis-host
    - secretKey: platform_redis_port
      remoteRef:
        key: dev-backend-secrets
        property: platform-redis-port
    - secretKey: platform_redis_password
      remoteRef:
        key: dev-backend-secrets
        property: platform-redis-password
    - secretKey: platform_encryption_key
      remoteRef:
        key: dev-backend-secrets
        property: platform-encryption-key
    - secretKey: platform_api_key
      remoteRef:
        key: dev-backend-secrets
        property: platform-api-key
---
# Development ExternalSecret for cert-manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-dev-secrets
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    platform.io/environment: "development"
    platform.io/component: "cert-manager"
    platform.io/managed-by: "external-secrets"
spec:
  refreshInterval: 60s

  secretStoreRef:
    name: kubernetes-secret-store
    kind: SecretStore

  target:
    name: acme-account-key
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        tls.key: "{{ .acme_account_private_key | toString }}"

  data:
    - secretKey: acme_account_private_key
      remoteRef:
        key: dev-backend-secrets
        property: acme-account-private-key

---
# Development ExternalSecret for external-dns
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-dev-secrets
  namespace: external-dns
  labels:
    app.kubernetes.io/name: external-dns
    platform.io/environment: "development"
    platform.io/component: "external-dns"
    platform.io/managed-by: "external-secrets"
spec:
  refreshInterval: 60s

  secretStoreRef:
    name: kubernetes-secret-store
    kind: SecretStore

  target:
    name: azure-dns-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        azure.json: |
          {
            "tenantId": "{{ .azure_tenant_id | toString }}",
            "subscriptionId": "{{ .azure_subscription_id | toString }}",
            "resourceGroup": "{{ .dns_resource_group | toString }}",
            "aadClientId": "{{ .external_dns_client_id | toString }}",
            "aadClientSecret": "{{ .external_dns_client_secret | toString }}"
          }

  data:
    - secretKey: azure_tenant_id
      remoteRef:
        key: dev-backend-secrets
        property: azure-tenant-id
    - secretKey: azure_subscription_id
      remoteRef:
        key: dev-backend-secrets
        property: azure-subscription-id
    - secretKey: dns_resource_group
      remoteRef:
        key: dev-backend-secrets
        property: dns-resource-group
    - secretKey: external_dns_client_id
      remoteRef:
        key: dev-backend-secrets
        property: external-dns-client-id
    - secretKey: external_dns_client_secret
      remoteRef:
        key: dev-backend-secrets
        property: external-dns-client-secret
