# HTTP-01 ClusterIssuers for Istio Gateway
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-http01
  labels:
    deployment-agent: cert-manager-engineer
    component: cert-management
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: david@davidmarkgardiner.co.uk
    privateKeySecretRef:
      name: letsencrypt-prod-http01
    solvers:
    - http01:
        ingress:
          class: istio
          ingressTemplate:
            metadata:
              annotations:
                kubernetes.io/ingress.class: istio
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-http01
  labels:
    deployment-agent: cert-manager-engineer
    component: cert-management
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: david@davidmarkgardiner.co.uk
    privateKeySecretRef:
      name: letsencrypt-staging-http01
    solvers:
    - http01:
        ingress:
          class: istio
          ingressTemplate:
            metadata:
              annotations:
                kubernetes.io/ingress.class: istio