---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-v2
  namespace: tenant-b
  labels:
    app: podinfo
    version: v2
    deployment-agent: istio-engineer
    test-scenario: development-primary
    tenant: tenant-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
      version: v2
  template:
    metadata:
      labels:
        app: podinfo
        version: v2
        tenant: tenant-b
        environment: development
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: istio-tenant-b
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:6.6.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
            - name: http-metrics
              containerPort: 9797
              protocol: TCP
            - name: grpc
              containerPort: 9999
              protocol: TCP
          command:
            - ./podinfo
            - --port=9898
            - --port-metrics=9797
            - --grpc-port=9999
            - --grpc-service-name=podinfo
            - --level=debug
            - --random-delay=true
            - --random-error=true # Enable random errors for chaos testing
          env:
            - name: PODINFO_UI_COLOR
              value: "#ff6b35" # Orange for development v2
            - name: PODINFO_UI_MESSAGE
              value: "Development Podinfo V2 - Tenant B (Primary)"
            - name: PODINFO_BACKEND_URL
              value: "http://redis.tenant-b.svc.cluster.local:6379"
            - name: PODINFO_CACHE_SERVER
              value: "redis://redis.tenant-b.svc.cluster.local:6379"
            - name: PODINFO_CONFIG_PATH
              value: "/etc/podinfo/config"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /etc/podinfo
              readOnly: true
      volumes:
        - name: tmp
          emptyDir: {}
        - name: config
          configMap:
            name: podinfo-config-dev
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
