---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-v3
  namespace: tenant-b
  labels:
    app: podinfo
    version: v3
    deployment-agent: istio-engineer
    test-scenario: experimental-features
    tenant: tenant-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
      version: v3
  template:
    metadata:
      labels:
        app: podinfo
        version: v3
        tenant: tenant-b
        environment: development
        experimental: "true"
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: istio-tenant-b
      containers:
      - name: podinfo
        image: stefanprodan/podinfo:6.6.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        - name: http-metrics
          containerPort: 9797
          protocol: TCP
        - name: grpc
          containerPort: 9999
          protocol: TCP
        command:
        - ./podinfo
        - --port=9898
        - --port-metrics=9797
        - --grpc-port=9999
        - --grpc-service-name=podinfo
        - --level=debug
        - --random-delay=true
        - --random-error=true
        - --unhealthy-after=60s  # Become unhealthy after 60 seconds (chaos testing)
        env:
        - name: PODINFO_UI_COLOR
          value: "#9c27b0"  # Purple for experimental v3
        - name: PODINFO_UI_MESSAGE
          value: "EXPERIMENTAL Podinfo V3 - Tenant B (Alpha Features)"
        - name: PODINFO_BACKEND_URL
          value: "http://redis.tenant-b.svc.cluster.local:6379"
        - name: PODINFO_CACHE_SERVER
          value: "redis://redis.tenant-b.svc.cluster.local:6379"
        - name: PODINFO_JWS_KEY
          value: "H4sIAKE/MVQAA92QQWqEMBiFryIhW40m"  # Experimental JWT features
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"  # Higher memory for experimental features
            cpu: "500m"      # Higher CPU for testing
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10  # Very tolerant for experimental features
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always