---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: tenant-b
  labels:
    app: redis
    deployment-agent: istio-engineer
    tenant: tenant-b
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        tenant: tenant-b
        environment: development
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: istio-tenant-b
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          command:
            - redis-server
            - --appendonly
            - "yes"
            - --maxmemory
            - "128mb"
            - --maxmemory-policy
            - "allkeys-lru"
            - --loglevel
            - "debug" # More verbose logging in development
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: redis-data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: tenant-b
  labels:
    app: redis
    deployment-agent: istio-engineer
    tenant: tenant-b
    environment: development
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
  selector:
    app: redis
