# Production ClusterSecretStore for Azure Key Vault
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
  labels:
    platform.io/component: "external-secrets"
    platform.io/tier: "system"
  annotations:
    platform.io/description: "Production Azure Key Vault secret store"
    platform.io/keyvault: "aks-prod-keyvault"
spec:
  provider:
    azurekv:
      # Production Key Vault with RBAC authorization
      tenantId: "${AZURE_TENANT_ID}"
      vaultUrl: "https://aks-prod-keyvault.vault.azure.net"
      authType: WorkloadIdentity
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets-system

  # Refresh interval for the store
  refreshInterval: 15m

  # Retry configuration for production resilience
  retrySettings:
    maxRetries: 5
    retryInterval: 30s
---
# Secondary ClusterSecretStore for fallback scenarios
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-backup
  labels:
    platform.io/component: "external-secrets"
    platform.io/tier: "system"
    platform.io/role: "backup"
  annotations:
    platform.io/description: "Backup Azure Key Vault secret store for disaster recovery"
spec:
  provider:
    azurekv:
      # Same vault but different configuration for backup scenarios
      tenantId: "${AZURE_TENANT_ID}"
      vaultUrl: "https://aks-prod-keyvault.vault.azure.net"
      authType: WorkloadIdentity
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets-system

  refreshInterval: 1h
  retrySettings:
    maxRetries: 3
    retryInterval: 60s

---
# Kubernetes secret store for development and testing
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kubernetes-secret-store
  namespace: external-secrets-system
  labels:
    platform.io/component: "external-secrets"
    platform.io/environment: "development"
  annotations:
    platform.io/description: "Kubernetes-based secret store for development"
spec:
  provider:
    kubernetes:
      remoteNamespace: external-secrets-system
      auth:
        serviceAccount:
          name: external-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: external-secrets-system
          key: ca.crt

  refreshInterval: 5m
