# Cert-Manager Helm Values for Azure Workload Identity
installCRDs: false  # CRDs already exist

global:
  logLevel: 2

replicaCount: 1

serviceAccount:
  create: true
  annotations:
    azure.workload.identity/client-id: "1317ba0a-60d3-4f05-b41e-483ed1d6acb3"
  labels:
    azure.workload.identity/use: "true"

podLabels:
  azure.workload.identity/use: "true"

securityContext:
  fsGroup: 1001

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  kubernetes.io/os: linux

webhook:
  replicaCount: 1
  serviceAccount:
    create: true
    annotations:
      azure.workload.identity/client-id: "1317ba0a-60d3-4f05-b41e-483ed1d6acb3"
    labels:
      azure.workload.identity/use: "true"
  
  podLabels:
    azure.workload.identity/use: "true"
  
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

cainjector:
  replicaCount: 1
  serviceAccount:
    create: true
    annotations:
      azure.workload.identity/client-id: "1317ba0a-60d3-4f05-b41e-483ed1d6acb3"
    labels:
      azure.workload.identity/use: "true"
  
  podLabels:
    azure.workload.identity/use: "true"
  
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

startupapicheck:
  enabled: true
  serviceAccount:
    create: true
    annotations:
      azure.workload.identity/client-id: "1317ba0a-60d3-4f05-b41e-483ed1d6acb3"
    labels:
      azure.workload.identity/use: "true"
  
  podLabels:
    azure.workload.identity/use: "true"