apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: argo
  labels:
    app.kubernetes.io/name: argo-workflows
    app.kubernetes.io/component: workflow-controller
    app.kubernetes.io/part-of: platform-api
    managed-by: flux
  annotations:
    # Azure Workload Identity annotations
    azure.workload.identity/client-id: "${AZURE_CLIENT_ID}"
    azure.workload.identity/tenant-id: "${AZURE_TENANT_ID}"
    azure.workload.identity/service-account-token-expiration: "86400"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-server
  namespace: argo
  labels:
    app.kubernetes.io/name: argo-workflows
    app.kubernetes.io/component: argo-server
    app.kubernetes.io/part-of: platform-api
    managed-by: flux
  annotations:
    # Azure Workload Identity annotations for server
    azure.workload.identity/client-id: "${AZURE_CLIENT_ID}"
    azure.workload.identity/tenant-id: "${AZURE_TENANT_ID}"
    azure.workload.identity/service-account-token-expiration: "86400"
automountServiceAccountToken: true
---
# ServiceAccount for executing workflows
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-executor
  namespace: argo
  labels:
    app.kubernetes.io/name: argo-workflows
    app.kubernetes.io/component: workflow-executor
    app.kubernetes.io/part-of: platform-api
    managed-by: flux
  annotations:
    azure.workload.identity/client-id: "${AZURE_CLIENT_ID}"
    azure.workload.identity/tenant-id: "${AZURE_TENANT_ID}"
automountServiceAccountToken: true
