---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: demo-virtualservice
  namespace: istio-demo
spec:
  hosts:
    - "demo.istio.local"
  gateways:
    - aks-istio-ingress/istio-demo-gateway
  http:
    - match:
        - headers:
            canary:
              exact: "true"
      route:
        - destination:
            host: podinfo
            subset: v2
          weight: 100
      timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
    - route:
        - destination:
            host: podinfo
            subset: v1
          weight: 90
        - destination:
            host: podinfo
            subset: v2
          weight: 10
      timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: staging-virtualservice
  namespace: istio-staging
spec:
  hosts:
    - "staging.istio.local"
  gateways:
    - aks-istio-ingress/istio-demo-gateway
  http:
    - match:
        - uri:
            prefix: "/v2"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: podinfo
            subset: v2
          weight: 100
      fault:
        delay:
          percentage:
            value: 0.1
          fixedDelay: 5s
      timeout: 15s
    - route:
        - destination:
            host: podinfo
            subset: v1
          weight: 100
      timeout: 15s
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: production-virtualservice
  namespace: istio-production
spec:
  hosts:
    - "prod.istio.local"
  gateways:
    - aks-istio-ingress/istio-demo-gateway
  http:
    - route:
        - destination:
            host: podinfo
            subset: v1
          weight: 100
      timeout: 5s
      retries:
        attempts: 5
        perTryTimeout: 2s
        retryOn: 5xx
