---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: podinfo-destination-rule
  namespace: istio-demo
spec:
  host: podinfo
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 2
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
      minHealthPercent: 50
    loadBalancer:
      simple: LEAST_CONN
  subsets:
  - name: v1
    labels:
      version: "6.0.0"
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 20
        http:
          http1MaxPendingRequests: 20
          maxRequestsPerConnection: 5
  - name: v2
    labels:
      version: "6.0.1"
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 5
        http:
          http1MaxPendingRequests: 5
          maxRequestsPerConnection: 1
      outlierDetection:
        consecutive5xxErrors: 2
        interval: 15s
        baseEjectionTime: 15s
        maxEjectionPercent: 100
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: podinfo-destination-rule
  namespace: istio-staging
spec:
  host: podinfo
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 15
      http:
        http1MaxPendingRequests: 15
        maxRequestsPerConnection: 3
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 60s
      baseEjectionTime: 60s
      maxEjectionPercent: 30
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels:
      version: "6.0.0"
  - name: v2
    labels:
      version: "6.0.1"
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: podinfo-destination-rule
  namespace: istio-production
spec:
  host: podinfo
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 50
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
        h2UpgradePolicy: UPGRADE
    loadBalancer:
      simple: LEAST_CONN
    outlierDetection:
      consecutive5xxErrors: 3
      consecutiveGatewayErrors: 3
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
      minHealthPercent: 50
  subsets:
  - name: v1
    labels:
      version: "6.0.0"
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 100
        http:
          http1MaxPendingRequests: 100
          maxRequestsPerConnection: 20
  - name: v2
    labels:
      version: "6.0.1"