apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: platform-api-dr
  namespace: platform-system
  labels:
    app: platform-api
    platform.io/component: "platform-api"
spec:
  host: platform-api.platform-system.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        http2MaxRequests: 100
        maxRequestsPerConnection: 10
        maxRetries: 3
    outlierDetection:
      consecutiveErrors: 3
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50