apiVersion: containerservice.azure.com/v1api20210501
kind: ManagedCluster
metadata:
  name: test-aks-westeurope
  namespace: test
  labels:
    azure-resource: managed-cluster
    azure-location: westeurope
    managed-by: azure-service-operator
    istio-enabled: "true"
    validation-mode: dry-run
spec:
  azureName: test-aks-westeurope
  location: westeurope
  owner:
    name: test-rg-westeurope
  dnsPrefix: testakswesteurope
  kubernetesVersion: "1.33.1"
  enableRBAC: true
  disableLocalAccounts: true
  # Identity Configuration with User Assigned Identity
  identity:
    type: UserAssigned
    userAssignedIdentities:
    - reference:
        name: test-identity-westeurope
  # AAD and RBAC Configuration
  aadProfile:
    enableAzureRBAC: true
    managed: true
  # Network Profile with Istio-compatible settings
  networkProfile:
    networkPlugin: azure
    networkPluginMode: overlay
    networkPolicy: cilium
    networkDataplane: cilium
    serviceCidr: 10.0.0.0/16
    dnsServiceIP: 10.0.0.10
    podCidr: 10.244.0.0/16
    loadBalancerSku: standard
  # Agent Pool Profile
  agentPoolProfiles:
  - name: systempool
    mode: System
    count: 3
    enableAutoScaling: true
    minCount: 1
    maxCount: 5
    vmSize: Standard_D2s_v3
    availabilityZones: ["1", "2", "3"]
    osDiskType: Managed
    osDiskSizeGB: 128
    osType: Linux
    osSKU: AzureLinux
    maxPods: 30
    enableNodePublicIP: false
  # Auto Upgrade Configuration
  autoUpgradeProfile:
    upgradeChannel: stable
    nodeOSUpgradeChannel: NodeImage
  # Addon Profiles
  addonProfiles:
    azureKeyvaultSecretsProvider:
      enabled: true
      config:
        enableSecretRotation: "true"
    azurepolicy:
      enabled: true
  # Service Principal Profile
  servicePrincipalProfile:
    clientId: msi
  # Node Resource Group
  nodeResourceGroup: test-aks-nodes-westeurope
  # Tags
  tags:
    environment: development
    project: test-project
    managedBy: azure-service-operator
    istio-enabled: "true"
    created-by: claude-code