# External Secrets configuration for Platform UI
# This file defines comprehensive secret synchronization from Azure Key Vault
# for secure runtime configuration injection

---
# Main Platform UI Configuration Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-ui-config
  namespace: platform-system
  labels:
    app.kubernetes.io/name: platform-ui
    app.kubernetes.io/component: frontend
    platform.io/managed-by: external-secrets
    platform.io/secret-type: configuration
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  
  target:
    name: platform-ui-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: platform-ui
          platform.io/secret-type: configuration
          platform.io/managed-by: external-secrets
      data:
        # Runtime configuration JSON for injection into the container
        config.json: |
          {
            "apiUrl": "{{ .apiUrl }}",
            "authEnabled": {{ .authEnabled | default "true" }},
            "environment": "{{ .environment | default "production" }}",
            "features": {
              "darkMode": {{ .featureDarkMode | default "true" }},
              "analytics": {{ .featureAnalytics | default "true" }},
              "costTracking": {{ .featureCostTracking | default "true" }},
              "debugMode": {{ .featureDebugMode | default "false" }}
            },
            "oauth": {
              "clientId": "{{ .oauthClientId }}",
              "authority": "{{ .oauthAuthority }}",
              "redirectUri": "{{ .oauthRedirectUri }}",
              "scopes": ["User.Read", "Directory.Read.All"]
            },
            "monitoring": {
              "enableMetrics": {{ .monitoringEnableMetrics | default "false" }},
              "enableTracing": {{ .monitoringEnableTracing | default "false" }}
            }
          }
        
        # Environment variables for build-time injection (if needed)
        VITE_API_URL: "{{ .apiUrl }}"
        VITE_AUTH_ENABLED: "{{ .authEnabled | default "true" }}"
        VITE_ENVIRONMENT: "{{ .environment | default "production" }}"
        VITE_OAUTH_CLIENT_ID: "{{ .oauthClientId }}"
        VITE_OAUTH_AUTHORITY: "{{ .oauthAuthority }}"
        VITE_OAUTH_REDIRECT_URI: "{{ .oauthRedirectUri }}"
        VITE_FEATURE_DARK_MODE: "{{ .featureDarkMode | default "true" }}"
        VITE_FEATURE_ANALYTICS: "{{ .featureAnalytics | default "true" }}"
        VITE_FEATURE_COST_TRACKING: "{{ .featureCostTracking | default "true" }}"
        VITE_DEBUG_MODE: "{{ .featureDebugMode | default "false" }}"
        VITE_ENABLE_METRICS: "{{ .monitoringEnableMetrics | default "false" }}"
        VITE_ENABLE_TRACING: "{{ .monitoringEnableTracing | default "false" }}"
  
  data:
    # Core API Configuration
    - secretKey: apiUrl
      remoteRef:
        key: platform-ui-api-url
        
    - secretKey: environment
      remoteRef:
        key: platform-ui-environment
        
    # Authentication Configuration
    - secretKey: authEnabled
      remoteRef:
        key: platform-ui-auth-enabled
        
    - secretKey: oauthClientId
      remoteRef:
        key: platform-azure-client-id  # Reuse the same client ID as API
        
    - secretKey: oauthAuthority
      remoteRef:
        key: platform-ui-oauth-authority
        
    - secretKey: oauthRedirectUri
      remoteRef:
        key: platform-ui-oauth-redirect-uri
        
    # Feature Flags
    - secretKey: featureDarkMode
      remoteRef:
        key: platform-ui-feature-darkmode
        
    - secretKey: featureAnalytics
      remoteRef:
        key: platform-ui-feature-analytics
        
    - secretKey: featureCostTracking
      remoteRef:
        key: platform-ui-feature-cost-tracking
        
    - secretKey: featureDebugMode
      remoteRef:
        key: platform-ui-feature-debug-mode
        
    # Monitoring Configuration
    - secretKey: monitoringEnableMetrics
      remoteRef:
        key: platform-ui-monitoring-enable-metrics
        
    - secretKey: monitoringEnableTracing
      remoteRef:
        key: platform-ui-monitoring-enable-tracing

---
# Build-time Secrets (for CI/CD pipeline)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-ui-build-secrets
  namespace: platform-system
  labels:
    app.kubernetes.io/name: platform-ui
    app.kubernetes.io/component: frontend
    platform.io/managed-by: external-secrets
    platform.io/secret-type: build
spec:
  refreshInterval: 24h
  
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  
  target:
    name: platform-ui-build-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: platform-ui
          platform.io/secret-type: build
          platform.io/managed-by: external-secrets
      data:
        # Build-time environment variables
        VITE_BUILD_VERSION: "{{ .buildVersion | default "1.0.0" }}"
        VITE_BUILD_DATE: "{{ .buildDate | default "2024-01-01" }}"
        VITE_BUILD_COMMIT: "{{ .buildCommit | default "unknown" }}"
        
        # Container registry credentials (if needed for private images)
        DOCKER_REGISTRY_URL: "{{ .dockerRegistryUrl | default "" }}"
        DOCKER_REGISTRY_USERNAME: "{{ .dockerRegistryUsername | default "" }}"
        DOCKER_REGISTRY_PASSWORD: "{{ .dockerRegistryPassword | default "" }}"
  
  data:
    - secretKey: buildVersion
      remoteRef:
        key: platform-ui-build-version
      optional: true
        
    - secretKey: buildDate
      remoteRef:
        key: platform-ui-build-date
      optional: true
        
    - secretKey: buildCommit
      remoteRef:
        key: platform-ui-build-commit
      optional: true
        
    - secretKey: dockerRegistryUrl
      remoteRef:
        key: platform-docker-registry-url
      optional: true
        
    - secretKey: dockerRegistryUsername
      remoteRef:
        key: platform-docker-registry-username
      optional: true
        
    - secretKey: dockerRegistryPassword
      remoteRef:
        key: platform-docker-registry-password
      optional: true