apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-config
  namespace: external-dns
data:
  azure.json: |
    {
      "useManagedIdentityExtension": true,
      "useWorkloadIdentityExtension": true
    }
