apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
  annotations:
    azure.workload.identity/client-id: "721782e9-90d6-4563-8e92-a0889337243e"
  labels:
    azure.workload.identity/use: "true"