apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
  annotations:
    azure.workload.identity/client-id: "${clientId}"
  labels:
    azure.workload.identity/use: "true"
