apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 5m
  path: ./apps/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: aso-flux
    namespace: flux-system
  timeout: 5m
  wait: true