apiVersion: managedidentity.azure.com/v1api20181130
kind: UserAssignedIdentity
metadata:
  name: aks-production-identity
  namespace: aso
  labels:
    azure-resource: user-assigned-identity
    azure-location: westeurope
    managed-by: azure-service-operator
    istio-enabled: "true"
    validation-mode: dry-run
spec:
  location: westeurope
  azureName: aks-production-identity
  owner:
    name: rg-production-aks-westeurope
  tags:
    environment: production
    purpose: aks-cluster-identity
    managed-by: aso
    created-by: claude-code