apiVersion: containerservice.azure.com/v1api20210501
kind: ManagedCluster
metadata:
  name: aks-production-cluster
  namespace: aso
  labels:
    azure-resource: managed-cluster
    azure-location: westeurope
    managed-by: azure-service-operator
    istio-enabled: "true"
    validation-mode: dry-run
spec:
  azureName: aks-production-cluster
  location: westeurope
  owner:
    name: rg-production-aks-westeurope
  operatorSpec:
    configMaps:
      oidcIssuerProfile:
        name: aks-oidc-config-prod
        key: issuer-url
  dnsPrefix: aks-production-cluster-k8s
  kubernetesVersion: "1.33"
  linuxProfile:
    adminUsername: localadmin
    ssh:
      publicKeys:
        - keyData: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7... # Placeholder - replace with actual key
  # Node provisioning with auto mode (NAP)
  nodeProvisioningProfile:
    mode: Auto
  # Identity Configuration
  identity:
    type: UserAssigned
    userAssignedIdentities:
    - reference:
        name: aks-production-identity
        group: managedidentity.azure.com
        kind: UserAssignedIdentity
  # AAD and RBAC Configuration
  aadProfile:
    enableAzureRBAC: true
    managed: true
    adminGroupObjectIDs:
    - 00000000-0000-0000-0000-000000000000  # Replace with actual admin group ID
  enableRBAC: true
  disableLocalAccounts: true
  # Network Profile with Istio compatibility
  networkProfile:
      networkPlugin: azure
      networkPluginMode: overlay
      networkPolicy: cilium
      networkDataplane: cilium
      serviceCidr: 10.0.0.0/16
      dnsServiceIP: 10.0.0.10
      podCidr: 10.244.0.0/16
      ipFamilies: ["IPv4"]
      loadBalancerSku: standard
      outboundType: loadBalancer
 
  # API Server Access
  apiServerAccessProfile:
    enablePrivateCluster: false
    enablePrivateClusterPublicFQDN: false
    disableRunCommand: true
  agentPoolProfiles:
  - name: systempool
    mode: System
    count: 3
    enableAutoScaling: true
    minCount: 2
    maxCount: 5
    vmSize: Standard_DS2_v2
    availabilityZones: ["1", "2", "3"]
    osDiskType: Managed
    osDiskSizeGB: 100
    osType: Linux
    osSKU: AzureLinux
    maxPods: 30
    enableNodePublicIP: false
    enableEncryptionAtHost: true
    enableUltraSSD: false
    enableFIPS: false
    kubeletDiskType: OS
    nodeLabels:
      nodepool-type: system
      environment: production
      zone-redundant: "true"
    kubeletConfig:
      cpuManagerPolicy: static
      topologyManagerPolicy: best-effort
      allowedUnsafeSysctls: []
      containerLogMaxFiles: 5
      containerLogMaxSizeMB: 50
      cpuCfsQuota: true
      failSwapOn: true
      imageGcHighThreshold: 85
      imageGcLowThreshold: 80
      podMaxPids: 1024
    linuxOSConfig:
      sysctls:
        vmMaxMapCount: 65530
        netCoreRmemMax: 134217728
        netCoreWmemMax: 134217728
        netIpv4TcpTwReuse: true
        netNetfilterNfConntrackMax: 131072
    securityProfile:
      enableSecureBoot: true
      enableVTPM: true
      sshAccess: Disabled
    upgradeSettings:
      maxSurge: "33%"
  identityProfile:
    kubeletidentity:
      resourceReference:
        name: aks-production-identity
        group: managedidentity.azure.com
        kind: UserAssignedIdentity
  # Auto Upgrade Configuration
  autoUpgradeProfile:
    upgradeChannel: patch
    nodeOSUpgradeChannel: NodeImage
  # Auto Scaler Profile - Fine-tuned for production
  autoScalerProfile:
    expander: least-waste
    max-empty-bulk-delete: "10"
    max-graceful-termination-sec: "600"
    max-node-provision-time: "15m"
    max-total-unready-percentage: "45"
    new-pod-scale-up-delay: "0s"
    ok-total-unready-count: "3"
    scale-down-delay-after-add: "10m"
    scale-down-delay-after-delete: "10s"
    scale-down-delay-after-failure: "3m"
    scale-down-unneeded-time: "10m"
    scale-down-unready-time: "20m"
    scale-down-utilization-threshold: "0.5"
    scan-interval: "10s"
    skip-nodes-with-local-storage: "false"
    skip-nodes-with-system-pods: "true"
  # Security Profile
  securityProfile:
    workloadIdentity:
      enabled: true
    imageCleaner:
      enabled: true
      intervalHours: 24
    defender:
      securityMonitoring:
        enabled: true
  # Storage Profile
  storageProfile:
    diskCSIDriver:
      enabled: true
    fileCSIDriver:
      enabled: true
    snapshotController:
      enabled: true
  # Addon Profiles
  addonProfiles:
    azureKeyvaultSecretsProvider:
      enabled: true
      config:
        enableSecretRotation: "true"
        rotationPollInterval: "2m"
    azurepolicy:
      enabled: true
      config:
        version: "v2"
  # Workload Auto Scaler with KEDA
  workloadAutoScalerProfile:
    keda:
      enabled: true
  # OIDC Issuer - Required for workload identity
  oidcIssuerProfile:
    enabled: true
  # Azure Monitor Profile
  azureMonitorProfile:
    metrics:
      enabled: false
      kubeStateMetrics:
        metricLabelsAllowlist: "namespaces=[owner, swID]"
  serviceMeshProfile:
    mode: Istio
    istio:
      components:
        ingressGateways:
          - enabled: true
            mode: External
      revisions:
        - asm-1-25
  podIdentityProfile:
    enabled: false
    userAssignedIdentityExceptions:
        - name: k8s-control-plane-exception
          namespace: kube-system
          podLabels:
            kubernetes.azure.com/managedby: aks
  # Resource group for node resources
  nodeResourceGroup: MC_rg-production-aks-westeurope_aks-production-cluster_westeurope
  # Service Principal Profile
  servicePrincipalProfile:
    clientId: msi
  # Tags
  tags:
    environment: production
    project: aks-production
    costCenter: it-infrastructure
    managedBy: azure-service-operator
    billingReference: prod-aks-001
    opEnvironment: production
    cmdbReference: aks-prod-we-001
    Owner: platform-team
    Status: active
    Team: platform-engineering
    DeployedBy: claude-code