# Azure Policy Assignment for SOC 2 Compliance
apiVersion: authorization.azure.com/v1api20220401
kind: PolicyAssignment
metadata:
  name: soc2-compliance-policy
  namespace: azure-system
  labels:
    component: compliance
    framework: soc2
    managed-by: aso
spec:
  # Scope to the entire resource group
  scope: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/at39473-weu-dev-prod
  
  # SOC 2 Initiative (built-in)
  policyDefinitionId: /providers/Microsoft.Authorization/policySetDefinitions/89c6cddc-1c73-4ac1-b19c-54d1a15a42f2
  
  displayName: "SOC 2 Type II Compliance"
  description: "Implements SOC 2 Type II security controls for production environment"
  
  # Use managed identity for policy remediation
  identity:
    type: SystemAssigned
  
  # Assignment parameters
  parameters:
    # Enable automatic remediation where possible
    effect:
      value: "AuditIfNotExists"
    
    # Include specific compliance requirements
    includeArcMachines:
      value: false
  
  # Policy enforcement mode
  enforcementMode: Default  # Set to DoNotEnforce for testing
  
  metadata:
    category: "Security Center"
    compliance-framework: "SOC2"
    remediation: "automatic"
  
  tags:
    compliance: soc2-type2
    enforcement: enabled
    auto-remediation: enabled

---
# Azure Policy Assignment for GDPR Compliance
apiVersion: authorization.azure.com/v1api20220401
kind: PolicyAssignment
metadata:
  name: gdpr-compliance-policy
  namespace: azure-system
  labels:
    component: compliance
    framework: gdpr
spec:
  scope: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/at39473-weu-dev-prod
  
  # Custom GDPR initiative
  policyDefinitionId: /providers/Microsoft.Authorization/policySetDefinitions/c5447c04-a4d7-4ba8-a263-c9ee321a6858
  
  displayName: "GDPR Data Protection Compliance"
  description: "Ensures GDPR compliance for data protection and privacy"
  
  identity:
    type: SystemAssigned
  
  parameters:
    # Data residency requirements
    allowedLocations:
      value: ["UK South", "UK West", "West Europe", "North Europe"]
    
    # Enable transparent data encryption
    transparentDataEncryptionOnSqlDatabasesEffect:
      value: "AuditIfNotExists"
  
  enforcementMode: Default
  
  tags:
    compliance: gdpr
    data-residency: eu-only
    encryption: required

---
# Azure Policy Assignment for ISO 27001 Compliance
apiVersion: authorization.azure.com/v1api20220401
kind: PolicyAssignment
metadata:
  name: iso27001-compliance-policy
  namespace: azure-system
  labels:
    component: compliance
    framework: iso27001
spec:
  scope: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/at39473-weu-dev-prod
  
  # ISO 27001 initiative
  policyDefinitionId: /providers/Microsoft.Authorization/policySetDefinitions/89c6cddc-1c73-4ac1-b19c-54d1a15a42f2
  
  displayName: "ISO 27001 Information Security Management"
  description: "Implements ISO 27001 security controls"
  
  identity:
    type: SystemAssigned
  
  parameters:
    # Security logging requirements
    logAnalyticsWorkspaceIdforVMReporting:
      value: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/at39473-weu-dev-prod/providers/Microsoft.OperationalInsights/workspaces/aks-prod-logs-workspace
  
  enforcementMode: Default
  
  tags:
    compliance: iso27001
    security-controls: enabled
    logging: centralized

---
# Custom Policy Definition for AKS Security Requirements
apiVersion: authorization.azure.com/v1api20220401
kind: PolicyDefinition
metadata:
  name: aks-security-requirements
  namespace: azure-system
  labels:
    component: custom-policies
    resource: aks
spec:
  displayName: "AKS Production Security Requirements"
  description: "Enforces security requirements for AKS clusters in production"
  
  policyType: Custom
  mode: Indexed
  
  # Policy rule in JSON format
  policyRule:
    if:
      allOf:
        - field: "type"
          equals: "Microsoft.ContainerService/managedClusters"
        - field: "tags['environment']"
          equals: "production"
    then:
      effect: "AuditIfNotExists"
      details:
        type: "Microsoft.ContainerService/managedClusters"
        existenceCondition:
          allOf:
            # Require RBAC to be enabled
            - field: "Microsoft.ContainerService/managedClusters/enableRBAC"
              equals: true
            # Require network policy
            - field: "Microsoft.ContainerService/managedClusters/networkProfile.networkPolicy"
              in: ["azure", "calico", "cilium"]
            # Require private cluster
            - field: "Microsoft.ContainerService/managedClusters/apiServerAccessProfile.enablePrivateCluster"
              equals: true
            # Require Azure AD integration
            - field: "Microsoft.ContainerService/managedClusters/aadProfile.managed"
              equals: true
  
  # Parameters for flexibility
  parameters:
    effect:
      type: String
      defaultValue: "AuditIfNotExists"
      allowedValues:
        - "AuditIfNotExists"
        - "Disabled"
      metadata:
        displayName: "Effect"
        description: "Enable or disable the execution of the policy"
  
  metadata:
    category: "Kubernetes"
    version: "1.0.0"

---
# Policy Assignment for custom AKS policy
apiVersion: authorization.azure.com/v1api20220401
kind: PolicyAssignment
metadata:
  name: aks-security-policy-assignment
  namespace: azure-system
spec:
  scope: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/at39473-weu-dev-prod
  
  policyDefinitionId: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/providers/Microsoft.Authorization/policyDefinitions/aks-security-requirements
  
  displayName: "AKS Production Security Policy"
  description: "Enforces security requirements for production AKS clusters"
  
  parameters:
    effect:
      value: "AuditIfNotExists"
  
  enforcementMode: Default

---
# Management Lock to prevent accidental deletion
apiVersion: authorization.azure.com/v1api20220401
kind: ManagementLock
metadata:
  name: production-resource-lock
  namespace: azure-system
  labels:
    component: resource-protection
    lock-type: cannot-delete
spec:
  # Lock the entire resource group
  scope: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/at39473-weu-dev-prod
  
  level: CanNotDelete  # Prevent deletion but allow modifications
  notes: "Production environment - deletion protection enabled"
  
  tags:
    protection-level: production
    lock-reason: accidental-deletion-prevention

---
# Resource Lock for Key Vault (additional protection)
apiVersion: authorization.azure.com/v1api20220401
kind: ManagementLock
metadata:
  name: keyvault-resource-lock
  namespace: azure-system
  labels:
    component: resource-protection
    resource: key-vault
spec:
  scope: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/at39473-weu-dev-prod/providers/Microsoft.KeyVault/vaults/aks-prod-keyvault
  
  level: ReadOnly  # Prevent modifications and deletion
  notes: "Key Vault contains critical secrets - full protection enabled"

---
# Security Center Contact for compliance notifications
apiVersion: security.azure.com/v1api20220501
kind: SecurityContact
metadata:
  name: production-security-contact
  namespace: azure-system
  labels:
    component: security-center
    purpose: compliance-notifications
spec:
  # Security contact configuration
  emails: "security@davidmarkgardiner.co.uk"
  phone: "+44-7700-900000"
  
  # Alert preferences
  alertNotifications:
    state: On
    minimalSeverity: Medium
  
  # Notify on alerts to admins
  notificationsByRole:
    state: On
    roles:
      - Owner
      - SecurityAdmin
  
  tags:
    notification-level: medium-and-above
    roles-notified: owner-security-admin

---
# Compliance Assessment for Resource Group
apiVersion: policyinsights.azure.com/v1api20220901
kind: PolicyAttestation
metadata:
  name: soc2-compliance-attestation
  namespace: azure-system
  labels:
    component: compliance-attestation
    framework: soc2
spec:
  # Scope to resource group
  resourceId: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/at39473-weu-dev-prod
  
  # Policy definition being attested
  policyDefinitionReferenceId: "soc2-compliance-policy"
  
  # Attestation details
  complianceState: Compliant
  expiresOn: "2024-12-31T23:59:59Z"
  
  # Evidence and justification
  evidence:
    - sourceUri: "https://example.com/soc2-audit-report.pdf"
      description: "SOC 2 Type II audit report demonstrating compliance"
  
  assessmentDate: "2024-01-15T00:00:00Z"
  comments: "SOC 2 compliance validated through independent audit"
  
  # Compliance metadata
  metadata:
    assignedBy: "compliance-team@davidmarkgardiner.co.uk"
    certificationBody: "Independent Auditor"
    complianceType: "soc2-type2"

---
# Budget Alert for compliance cost monitoring
apiVersion: consumption.azure.com/v1api20230501
kind: Budget
metadata:
  name: compliance-cost-budget
  namespace: azure-system
  labels:
    component: cost-management
    purpose: compliance-monitoring
spec:
  # Scope to the resource group
  scope: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/at39473-weu-dev-prod
  
  # Budget properties
  amount: 5000  # £5,000 monthly budget for compliance resources
  timeGrain: Monthly
  
  # Budget period
  timePeriod:
    startDate: "2024-01-01T00:00:00Z"
    endDate: "2024-12-31T23:59:59Z"
  
  # Budget filters for compliance resources only
  filter:
    dimensions:
      name: ResourceGroupName
      operator: In
      values:
        - at39473-weu-dev-prod
    tags:
      name: compliance
      operator: In
      values:
        - soc2
        - gdpr
        - iso27001
  
  # Notifications
  notifications:
    - enabled: true
      operator: GreaterThan
      threshold: 80  # Alert at 80% of budget
      contactEmails:
        - "finance@davidmarkgardiner.co.uk"
        - "devops@davidmarkgardiner.co.uk"
      contactRoles:
        - Owner
        - Contributor
      contactGroups: []
      thresholdType: Actual
    - enabled: true
      operator: GreaterThan
      threshold: 100  # Alert at 100% of budget
      contactEmails:
        - "finance@davidmarkgardiner.co.uk"
        - "devops@davidmarkgardiner.co.uk"
      contactRoles:
        - Owner
      contactGroups: []
      thresholdType: Forecasted
  
  tags:
    budget-type: compliance
    alert-thresholds: "80,100"
    cost-center: compliance-governance

---
# Role Assignment for compliance team
apiVersion: authorization.azure.com/v1api20220401
kind: RoleAssignment
metadata:
  name: compliance-team-reader
  namespace: azure-system
  labels:
    component: rbac
    team: compliance
spec:
  scope: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/at39473-weu-dev-prod
  
  # Security Reader role for compliance team
  roleDefinitionReference:
    armId: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/providers/Microsoft.Authorization/roleDefinitions/39bc4728-0917-49c7-9d2c-d95423bc2eb4
  
  # Principal ID would be set to compliance team group
  principalId: "12345678-1234-1234-1234-123456789012"  # Replace with actual group ID
  principalType: Group
  
  description: "Compliance team read access for audit purposes"

---
# Custom Policy for data classification requirements
apiVersion: authorization.azure.com/v1api20220401
kind: PolicyDefinition
metadata:
  name: data-classification-tagging
  namespace: azure-system
  labels:
    component: custom-policies
    purpose: data-classification
spec:
  displayName: "Require Data Classification Tags"
  description: "Ensures all resources storing data have proper classification tags"
  
  policyType: Custom
  mode: Indexed
  
  policyRule:
    if:
      allOf:
        - field: "type"
          in:
            - "Microsoft.Storage/storageAccounts"
            - "Microsoft.DBforPostgreSQL/flexibleServers"
            - "Microsoft.Cache/Redis"
            - "Microsoft.DocumentDB/databaseAccounts"
        - field: "tags['data-classification']"
          exists: false
    then:
      effect: "Deny"
      details:
        reason: "Data classification tag is required for all data storage resources"
  
  parameters:
    allowedClassifications:
      type: Array
      defaultValue: ["public", "internal", "confidential", "restricted"]
      metadata:
        displayName: "Allowed Data Classifications"
        description: "List of allowed data classification values"
  
  metadata:
    category: "Data Governance"
    compliance: "gdpr,soc2,iso27001"

---
# Assignment for data classification policy
apiVersion: authorization.azure.com/v1api20220401
kind: PolicyAssignment
metadata:
  name: data-classification-assignment
  namespace: azure-system
spec:
  scope: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/resourceGroups/at39473-weu-dev-prod
  
  policyDefinitionId: /subscriptions/133d5755-4074-4d6e-ad38-eb2a6ad12903/providers/Microsoft.Authorization/policyDefinitions/data-classification-tagging
  
  displayName: "Data Classification Enforcement"
  description: "Requires data classification tags on all storage resources"
  
  parameters:
    allowedClassifications:
      value: ["public", "internal", "confidential", "restricted"]
  
  enforcementMode: Default