---
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-api-config
  namespace: platform-system
  labels:
    app: platform-api
    platform.io/component: "platform-api"
    version: v1.1.0
  annotations:
    platform.io/version: "v1.1.0"
data:
  NODE_ENV: "production"
  KUBE_CONTEXT: "current"
  KUBE_NAMESPACE: "default"
  PORT: "3000"
  # JWT Configuration
  JWT_ISSUER: "platform-api"
  JWT_AUDIENCE: "platform-users"
  JWT_EXPIRES_IN: "24h"
  # CORS Configuration
  CORS_ORIGINS: "https://platform-ui.platform-system.svc.cluster.local,https://platform.aks.local"
  # Platform Configuration
  PLATFORM_DEFAULT_TIER: "small"
  PLATFORM_MAX_NAMESPACES_PER_TEAM: "50"
  PLATFORM_ALLOWED_FEATURES: "istio-injection,monitoring-enhanced,backup-enabled,gpu-access,database-access,external-ingress,argo-workflows"
  PLATFORM_COST_TRACKING: "true"
  PLATFORM_AUDIT_RETENTION_DAYS: "365"
  PLATFORM_ENABLE_ANALYTICS: "true"
  PLATFORM_ENABLE_RBAC: "true"
  # Rate Limiting Configuration (Production Values)
  RATE_LIMIT_WINDOW_MS: "900000" # 15 minutes
  RATE_LIMIT_MAX_REQUESTS: "1000" # Increased for production
  RATE_LIMIT_SKIP_SUCCESS: "false"
  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  # Database Configuration
  DB_HOST: "postgresql.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "platform"
  DB_USER: "platform"
  DB_SSL: "true"
  DB_POOL_MIN: "5"
  DB_POOL_MAX: "20"
  # Redis Configuration
  REDIS_HOST: "redis.database.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  # Argo Workflows Configuration
  ARGO_NAMESPACE: "argo"
  ARGO_SERVER_URL: "argo-server.argo.svc.cluster.local:2746"
  # Observability Configuration
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  HEALTH_CHECK_TIMEOUT: "5000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-api-azure-cm
  namespace: platform-system
  labels:
    app: platform-api
    platform.io/component: "platform-api"
    version: v1.1.0
data:
  subscriptionId: "SET_YOUR_SUBSCRIPTION_ID"
  tenantId: "SET_YOUR_TENANT_ID"
