apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-api-provisioner
  labels:
    platform.io/component: platform-api
    platform.io/resource-type: rbac
rules:
# Namespace management
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]

# Resource management within namespaces
- apiGroups: [""]
  resources: ["resourcequotas", "limitranges", "secrets", "configmaps", "services", "serviceaccounts"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]

# RBAC management
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]

# Network Policy management  
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]

# Pod and deployment monitoring
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list"]

# Metrics and monitoring
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-api-provisioner
  labels:
    platform.io/component: platform-api
    platform.io/resource-type: rbac
subjects:
- kind: ServiceAccount
  name: platform-api
  namespace: platform-system
roleRef:
  kind: ClusterRole
  name: platform-api-provisioner
  apiGroup: rbac.authorization.k8s.io