---
# Production External Secrets Configuration for Platform API
# This replaces the placeholder secret with proper Azure Key Vault integration
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: platform-system
  labels:
    app: platform-api
    platform.io/component: "platform-api"
    version: v1.1.0
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://platform-aks-kv.vault.azure.net/"
      serviceAccountRef:
        name: platform-api
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-api-secrets
  namespace: platform-system
  labels:
    app: platform-api
    platform.io/component: "platform-api"
    version: v1.1.0
  annotations:
    platform.io/description: "External secrets for Platform API from Azure Key Vault"
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: platform-api-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app: platform-api
          platform.io/component: "platform-api"
          version: v1.1.0
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: platform-api-jwt-secret
    - secretKey: db-password
      remoteRef:
        key: platform-api-db-password
    - secretKey: redis-password
      remoteRef:
        key: platform-api-redis-password
    - secretKey: azure-client-secret
      remoteRef:
        key: platform-api-azure-client-secret
    - secretKey: argo-token
      remoteRef:
        key: platform-api-argo-token
---
# Backup secret for development/testing (commented out for production)
# apiVersion: v1
# kind: Secret
# metadata:
#   name: platform-api-secrets-backup
#   namespace: platform-system
#   labels:
#     app: platform-api
#     platform.io/component: "platform-api"
# type: Opaque
# data:
#   jwt-secret: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=  # change-me-in-production
#   db-password: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=  # change-me-in-production
#   redis-password: ""  # Optional - empty if Redis doesn't require auth
