# This is a template for platform API secrets
# In production, these should be created through external secret management
# like Azure Key Vault or External Secrets Operator
apiVersion: v1
kind: Secret
metadata:
  name: platform-api-secrets
  namespace: platform-system
  labels:
    app: platform-api
    platform.io/component: "platform-api"
type: Opaque
data:
  # These are base64 encoded placeholder values
  # Replace with actual values from your secret management system
  jwt-secret: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=  # change-me-in-production
  db-password: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=  # change-me-in-production  
  redis-password: ""  # Optional - empty if Redis doesn't require auth
---
# NOTE: In production, use External Secrets Operator or similar:
# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: azure-keyvault-store
#   namespace: platform-system
# spec:
#   provider:
#     azurekv:
#       authType: WorkloadIdentity
#       vaultUrl: "https://your-keyvault.vault.azure.net/"
#       serviceAccountRef:
#         name: platform-api
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: platform-api-secrets
#   namespace: platform-system
# spec:
#   refreshInterval: 15m
#   secretStoreRef:
#     name: azure-keyvault-store
#     kind: SecretStore
#   target:
#     name: platform-api-secrets
#     creationPolicy: Owner
#   data:
#   - secretKey: jwt-secret
#     remoteRef:
#       key: platform-api-jwt-secret
#   - secretKey: db-password
#     remoteRef:
#       key: platform-api-db-password