---
apiVersion: v1
kind: Service
metadata:
  name: platform-api
  namespace: platform-system
  labels:
    app: platform-api
    platform.io/component: "platform-api"
    version: v1.1.0
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
    platform.io/description: "Platform API service for namespace-as-a-service"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: http
      protocol: TCP
  selector:
    app: platform-api
  sessionAffinity: None
