apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-api
  namespace: platform-system
  labels:
    app: platform-api
    platform.io/component: "platform-api"
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "${clientId}"
    platform.io/description: "Service account for Platform API with Azure Workload Identity"