apiVersion: v1
kind: Service
metadata:
  name: platform-api
  namespace: platform-system
  labels:
    app: platform-api
    platform.io/component: "platform-api"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: platform-api