apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-api
  namespace: platform-system
  labels:
    app: platform-api
    platform.io/component: "platform-api"
    azure.workload.identity/use: "true"
    version: v1.1.0
  annotations:
    azure.workload.identity/client-id: "$(platform-api-identity-cm:clientId)"
    platform.io/description: "Service account for Platform API with Azure Workload Identity and Kubernetes API access"
    platform.io/version: "v1.1.0"
automountServiceAccountToken: true
