---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-manager-network-policy
  namespace: cert-manager
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: istio-system
    ports:
    - protocol: TCP
      port: 9402  # metrics
  egress:
  - {}  # Allow all egress (needed for ACME challenges, DNS, etc.)
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: external-dns-network-policy
  namespace: external-dns
spec:
  podSelector:
    matchLabels:
      app: external-dns
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: istio-system
    ports:
    - protocol: TCP
      port: 7979  # metrics/health
  egress:
  - {}  # Allow all egress (needed for Azure DNS API, Kubernetes API, etc.)