apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: shared-services
  labels:
    tenant: shared
    deployment-agent: istio-engineer

resources:
  - monitoring-stack.yaml
  - jaeger-tracing.yaml
  - redis-cluster.yaml

namespace: shared-services

commonLabels:
  tenant: shared
  managed-by: flux
  deployment-agent: istio-engineer
  service-type: infrastructure

images:
- name: prom/prometheus
  newTag: "v2.48.0"
- name: grafana/grafana
  newTag: "10.2.0"
- name: jaegertracing/all-in-one
  newTag: "1.51"
- name: redis
  newTag: "7-alpine"

replicas:
- name: prometheus
  count: 1
- name: grafana
  count: 1
- name: jaeger
  count: 1
- name: redis-cluster
  count: 3

configMapGenerator:
- name: prometheus-config
  files:
  - prometheus.yml
- name: grafana-dashboards
  files:
  - istio-dashboard.json
  - podinfo-dashboard.json