---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: tenant-a
  labels:
    app: podinfo
    deployment-agent: istio-engineer
    tenant: tenant-a
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9797"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9898
    targetPort: http
    protocol: TCP
  - name: http-metrics
    port: 9797
    targetPort: http-metrics
    protocol: TCP
  - name: grpc
    port: 9999
    targetPort: grpc
    protocol: TCP
  selector:
    app: podinfo
---
# Headless service for direct pod access (testing purposes)
apiVersion: v1
kind: Service
metadata:
  name: podinfo-headless
  namespace: tenant-a
  labels:
    app: podinfo
    deployment-agent: istio-engineer
    tenant: tenant-a
    service-type: headless
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9898
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9999
    targetPort: grpc
    protocol: TCP
  selector:
    app: podinfo
# ---
# # ServiceMonitor for Prometheus scraping (if Prometheus Operator is used)
# # Commented out - requires Prometheus operator to be installed first
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: podinfo
#   namespace: tenant-a
#   labels:
#     app: podinfo
#     deployment-agent: istio-engineer
#     tenant: tenant-a
# spec:
#   selector:
#     matchLabels:
#       app: podinfo
#   endpoints:
#   - port: http-metrics
#     interval: 30s
#     path: /metrics
#     scheme: http
#   namespaceSelector:
#     matchNames:
#     - tenant-a