---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-demo-gateway
  namespace: aks-istio-ingress
spec:
  selector:
    istio: aks-istio-ingressgateway-internal
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "demo.istio.local"
    - "staging.istio.local"
    - "prod.istio.local"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "demo.istio.local"
    - "staging.istio.local"
    - "prod.istio.local"
    tls:
      mode: SIMPLE
      credentialName: istio-demo-tls
---
apiVersion: v1
kind: Secret
metadata:
  name: istio-demo-tls
  namespace: aks-istio-ingress
type: kubernetes.io/tls
data:
  # Self-signed certificate for demo purposes
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lVVStmUFFMZ2dsN1hoVzJCT2lKUzROZkZPU1hrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0V6RVJNQThHQTFVRUF3d0lhWE4wYVc4dWJHOWpZV3d3SGhjTk1qUXhNVEV5TXpJd01ETXlXaGNOTWpVeApNVEV5TXpJd01ETXlXakFUTVJFd0R3WURWUVFEREFocGMzUnBieTVzYjJOaGJEQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNU0g5aXBabzd1Y2RHNUMrT2FqUzlHR3dOTnM4YnJkN2xqOUVOb00Kck1uTHhDNUd3SGJUT3BmUmhCMUtWT3Y4RjZSRjNHT2FLNVZ6WXo4KzZWM1Y2YXM2RDU3cjREZ2luZ1Y2c05rbwp4TGkwbFJGNnZHZkc0WTY2TE5YT2RHRGhWbEJRZnF5dXFnUGpJK0xuOVBRU05rQXpHemdYZXh0TkNDVTFDVnNXCmYzVXNjNFhNa3A1V1VvWkdGTGFKVUZNRmRkT0VwT3h2cE10SXZvUTA4ZUJCa3V6RGRWOU9EZlRXR0pIdVh5eDkKKzUzdkJmWDVEYUtDbUViSmtaSzl2S1ZGcHhKVTZlajJmeHNqeFozRFBSUzJ5cnFFNXF3MXYzVExGSnZmY3BRWgpqR2hMT3RxSVZBMHRjZVVhbjVLTExzd3YzMVRvZ3hZRnBxYkdOK21vZEZPWnBGOENBd0VBQWFOUU1FNHdIUVlEClZSME9CQllFRkd2M1NaOXVKYUdmYUNYRHNUVzRuYk5pSDRDZWJvOGJNQjhHQTFVZEl3UVlNQmFBRkd2M1NaOXUKSmFHZmFDWERzVFc0bmJOaUg0Q2ViQWtHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUF4OEhmQ3VQdlNvZWZ1L3l2bwpLTnZCOE1DYzFLY1dOWDZrSEgrSTZ2UjlTdnpMQXFGK1ZmN2RzM3NuV0hhdCtWMHZKaXVOdWkwL2FwZUNuL2NXCmF3czJXRis3UT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRREVoL1lxV2FPN25IUnUKUXZqbW8wdlJoc0RUYlBHNjNlNVkvUkRhREt6Snk4UXVSc0IyMHpxWDBZUWRTbFRyL0Jla1JkeGptaXVWYzJNLwpQdWxkMWVtck9nK2U2K0E0SXA0RmVyRFpLTVM0dEpVUmVyeG54dUdPdWl6VnpuUmc0VlpRVUg2c3Jxb0Q0eVBpCjUvVDBFalpBTXhzNEYzc2JURGZRS1JRRGQwSDlNYXVWdU1neXFBVU5rdHhTWkhSZEFYUldjUWxMOTF4eWc5CjUwbWVwSE5oSlRaWXJCMGlTY3JKNklDd3pRZUJCa3V6RGRWOU9EZlRXR0pIdVh5eDkrNTN2QmZYNURhS0NtRWIKSmtaSzl2S1ZGcHhKVTZlajJmeHNqeFozRFBSUzJ5cnFFNXF3MXYzVExGSnZmY3BRWmpHaExPdHFJVkEwdGNlVQphbjVLTExzd3YzMVRvZ3hZRnBxYkdOK21vZEZPWnBGOENBd0VBQVFLQmdGWDVRUmVQVjhKY0RNb0wxbUUzR1BwClZNcXpRb0ZnWGJaVllWU2tRU1BCcW5SQTY2S1pLVFJDcjkxS3BrcERUSWczdTJqWTUzWnRDc3lCREI2YThCZ1UKdnVwR0w5TkpaNWRCSGJhOEQyVnVMbUdKdnRrWGlVVElJTGhqVlBXZnRjWW8zVTRkaUQzNXd2QmdkTUgzaDNGZgpRK1paaWhGWGJpV1Q3VlJ5UFdyaEFvR0JBUGZUQmt4TEVkSW52U0Q2SXQrTHdIL3NVSkN0K0d6eWlCUldOalJkCmFjL1VtTEw5SHRGb29jZ3JQUXhIVHhIeDdxaHRCbHhCY0llMFBxbzYrQzE1cGtYOXI5eVFhdDhSdmtnVEYwMTYKd1cwWGRqclU4VU0wa05NZjdRWFNjdGZmTGZGcDc4UVZvSzMxckhmbzgyRWNBTVdoN1hucjVJRTlTaExVSlBrbApOT3Q5QW9HQKF1UWQ5VmRFT1NzMnJNZktiNkRXZHNQNmVQSXA0bkpvSjNMdDhzaHFYM2dvbjNaVUNKTVRLZ04KSWxHS1B1Sy9mWmRPNVFQYXA4ZUEzbVNNYnZSR3RnODh5ZmJaN3VuWGJvM2Vqb0pNTGdCUjcvOUl4cW9Pdk1qTgpiZEVmL0FFK1NvZEExRW5TL2tCWGZjRjhXck5HOCsyQ0EvRjUxQWQrNjNRYUR6Q1BBb0dBSkFLZnJDSWlLUmQxCkp6NFR6NjFNUGhSV3MvY2hHOThhUk9HNUxtMnJqZCtadlc4SEJmVDJqTzNiRG95MEdkME9OSlZPSEt0N0hJaVIKZENsYUJhekhTc2UwMjAzcmg1M3ozNmRqWjN6ejBHSTJWRE1TOFNqdmRHWXM4SkNvN3FZZG1MZDNwOUFSakxqVQpyTldHSFhzL0E5R0FqQW5adW5yUnNIT2VaekVSa3JjQ2dZRUF4RVQyOHB0d3lDRVZGdU1VdGpzSTluVlUzWndGCkh2WC9lUUdWWXFGWVZOcXRLUkhrdDllSnZPYUl1YnJvZGVHbHlYTytwSXNGLzVzWnczZGVRNnFLN1dDdWFoUmoKZHNHbzdScWNxaG9ZSUpDV2lSeFBlTGVOelJVSzBHckRUSE1VVlJmcG5Makt6a05ZODBIUDhMcGVNQzJKeGhNVwpCbGNVTzhJbTVKST0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=