apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/infrastructure/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: aso-flux
    namespace: flux-system
  timeout: 10m
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: external-dns
      namespace: external-dns