apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    deployment-agent: istio-engineer
    component: cert-management
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: david@davidmarkgardiner.co.uk
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: istio
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    deployment-agent: istio-engineer
    component: cert-management
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: david@davidmarkgardiner.co.uk
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: istio