apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 15m
  timeout: 1m
  chart:
    spec:
      chart: cert-manager
      version: "v1.15.3"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  test:
    enable: true
  rollback:
    cleanupOnFail: true
  targetNamespace: cert-manager
  values:
    installCRDs: true
    startupapicheck:
      enabled: false
    global:
      leaderElection:
        namespace: "cert-manager"