apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: external-dns
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  test:
    enable: true
  rollback:
    cleanupOnFail: true
  targetNamespace: external-dns
  values:
    image:
      tag: "v0.18.0"
    sources:
      - service
      - ingress
      - istio-gateway
      - istio-virtualservice
    domainFilters:
      - davidmarkgardiner.co.uk
    provider:
      name: azure
    txtPrefix: externaldns-
    interval: 1m
    logLevel: info
    policy: sync
    env:
      - name: AZURE_CLIENT_ID
        valueFrom:
          configMapKeyRef:
            name: external-dns-identity-cm
            key: AZURE_CLIENT_ID
      - name: AZURE_AUTH_METHOD
        value: "wli"
    serviceAccount:
      create: true
      annotations:
        azure.workload.identity/client-id: "1bc849b8-d08e-4bb9-8e7d-11c04f3e310c"
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
      fsGroup: 65532
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
      requests:
        memory: "64Mi"
        cpu: "10m"
    livenessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 30
      timeoutSeconds: 5
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 5
      timeoutSeconds: 5
      periodSeconds: 10
      failureThreshold: 3