apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 15m
  timeout: 1m
  chart:
    spec:
      chart: external-dns
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  test:
    enable: true
  rollback:
    cleanupOnFail: true
  targetNamespace: external-dns
  values:
    image:
      tag: "v0.17.0"
    extraArgs:
      - --azure-config-file=/dev/null
      - --metrics-addr=0.0.0.0:7979
    sources:
      - service
      - ingress
      - istio-gateway
      - istio-virtualservice
    domainFilters:
      - davidmarkgardiner.co.uk
    provider: azure
    azure:
      resourceGroup: dns
      subscriptionId: "133d5755-4074-4d6e-ad38-eb2a6ad12903"
      aadClientId: "e651afda-3cfc-431b-ae58-e255232e61c8"
      useWorkloadIdentityExtension: true
      useManagedIdentityExtension: false
      azureConfigFile: ""
    txtOwnerId: external-dns
    interval: 1m
    logLevel: info
    policy: sync
    serviceAccount:
      create: true
      annotations:
        azure.workload.identity/client-id: "e651afda-3cfc-431b-ae58-e255232e61c8"
      labels:
        azure.workload.identity/use: "true"
    podLabels:
      azure.workload.identity/use: "true"
    env:
      - name: AZURE_AUTH_METHOD
        value: wli
      - name: AZURE_CLIENT_ID
        value: "e651afda-3cfc-431b-ae58-e255232e61c8"
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
      fsGroup: 65532
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
      requests:
        memory: "64Mi"
        cpu: "10m"
    livenessProbe:
      httpGet:
        path: /healthz
        port: http-metrics
      initialDelaySeconds: 30
      timeoutSeconds: 5
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /healthz
        port: http-metrics
      initialDelaySeconds: 5
      timeoutSeconds: 5
      periodSeconds: 10
      failureThreshold: 3