apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    deployment-agent: istio-engineer
    component: external-dns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    azure.workload.identity/use: "true"
    deployment-agent: istio-engineer
  annotations:
    azure.workload.identity/client-id: "e651afda-3cfc-431b-ae58-e255232e61c8"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    deployment-agent: istio-engineer
    component: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.0
        args:
        - --source=service
        - --source=ingress
        - --source=istio-gateway
        - --source=istio-virtualservice
        - --domain-filter=davidmarkgardiner.co.uk
        - --provider=azure
        - --azure-resource-group=dns
        - --azure-subscription-id=133d5755-4074-4d6e-ad38-eb2a6ad12903
        - --txt-owner-id=external-dns
        - --interval=1m
        - --log-level=info
        - --policy=sync
        env:
        - name: AZURE_AUTH_METHOD
          value: wli
        - name: AZURE_CLIENT_ID
          value: "e651afda-3cfc-431b-ae58-e255232e61c8"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
  labels:
    deployment-agent: istio-engineer
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods","nodes"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: ["networking.istio.io"]
  resources: ["gateways","virtualservices"]
  verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  labels:
    deployment-agent: istio-engineer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: external-dns