apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 15m
  timeout: 1m
  chart:
    spec:
      chart: external-dns
      version: "1.15.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  test:
    enable: true
  rollback:
    cleanupOnFail: true
  targetNamespace: external-dns
  values:
    image:
      tag: "v0.14.0"
    extraArgs:
      - --azure-config-file=/dev/null
    sources:
      - service
      - ingress
      - istio-gateway
      - istio-virtualservice
    domainFilters:
      - davidmarkgardiner.co.uk
    provider: azure
    azure:
      resourceGroup: dns
      subscriptionId: "133d5755-4074-4d6e-ad38-eb2a6ad12903"
      aadClientId: "e651afda-3cfc-431b-ae58-e255232e61c8"
      useWorkloadIdentityExtension: true
      useManagedIdentityExtension: false
      azureConfigFile: ""
    txtOwnerId: external-dns
    interval: 1m
    logLevel: info
    policy: sync
    serviceAccount:
      create: true
      annotations:
        azure.workload.identity/client-id: "e651afda-3cfc-431b-ae58-e255232e61c8"
      labels:
        azure.workload.identity/use: "true"
    podLabels:
      azure.workload.identity/use: "true"
    env:
      - name: AZURE_AUTH_METHOD
        value: wli
      - name: AZURE_CLIENT_ID
        value: "e651afda-3cfc-431b-ae58-e255232e61c8"
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
      requests:
        memory: "32Mi"
        cpu: "1m"