apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: istio-apps
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: infra
  url: https://github.com/davidgardiner/claude-aso
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./istio-apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: istio-apps
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo-v1
      namespace: tenant-a
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo-v1
      namespace: tenant-b
  dependsOn:
    - name: infrastructure
