apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-helmrepo.yaml
  - cert-manager-helmrelease.yaml
  - cert-manager-issuer.yaml
  - external-dns-helmrepo.yaml
  - external-dns-helmrelease.yaml
  - external-dns.yaml


