apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Infrastructure dependencies
  - infrastructure/cert-manager-kustomization.yaml
  - infrastructure/external-dns-kustomization.yaml
  
  # Application dependencies (depends on infrastructure)
  - certificates/cert-issuers-kustomization.yaml