apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - cert-manager/
  # - external-dns/

# Note: istio-apps should be deployed separately due to complexity
# Use: kubectl apply -k ../istio-apps/


