---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    deployment-agent: cert-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
  endpoints:
  - port: http-metrics
    interval: 60s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1  
kind: ServiceMonitor
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    app.kubernetes.io/name: external-dns
    deployment-agent: external-dns
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  endpoints:
  - port: http
    interval: 60s
    path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  name: external-dns-metrics
  namespace: external-dns
  labels:
    app.kubernetes.io/name: external-dns
spec:
  selector:
    app: external-dns
  ports:
  - name: http
    port: 7979
    targetPort: 7979