apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    name: platform-system
    managed-by: flux
    environment: production
  annotations:
    description: "Platform engineering namespace for namespace-as-a-service"
