apiVersion: kubernetesconfiguration.azure.com/v1api20241101
kind: FluxConfiguration
metadata:
  name: aso-flux
  namespace: azure-system
spec:
  azureName: aso-flux
  gitRepository:
    provider: Generic
    repositoryRef:
      branch: experiment/test-cluster-build
    url: https://github.com/davidmarkgardiner/claude-aso
  kustomizations:
    external-dns:
      path: ./apps/external-dns
      timeoutInSeconds: 600
      syncIntervalInSeconds: 120
      prune: true
      force: true
      postBuild:
        substitute:
          clientId: "1c0b7ee1-f55a-407c-946c-83254494df30"
          principalId: "896eea23-4c9d-4070-b883-6706ca9fbea3"
          tenantId: "550cfcda-8a2d-452c-ba71-d6bc6bf5bb31"
    cert-manager-base:
      path: ./apps/cert-manager-base
      timeoutInSeconds: 600
      syncIntervalInSeconds: 120
      prune: true
      force: true
      postBuild:
        substitute:
          clientId: "540fae85-49bc-4a56-946b-08518c7c5838"
          principalId: "50cf8e5f-835b-419b-958f-62207aa2242e"
          tenantId: "550cfcda-8a2d-452c-ba71-d6bc6bf5bb31"
    cert-manager-config:
      dependsOn: ["cert-manager-base"]
      path: ./apps/cert-manager-config
      timeoutInSeconds: 600
      syncIntervalInSeconds: 120
      prune: true
      force: true
      postBuild:
        substitute:
          clientId: "540fae85-49bc-4a56-946b-08518c7c5838"
          principalId: "50cf8e5f-835b-419b-958f-62207aa2242e"
          tenantId: "550cfcda-8a2d-452c-ba71-d6bc6bf5bb31"
    istio-apps:
      dependsOn: ["external-dns", "cert-manager-config"]
      path: ./istio-apps
      timeoutInSeconds: 600
      syncIntervalInSeconds: 120
      prune: true
      force: true
  namespace: azure-system
  owner:
    group: containerservice.azure.com
    kind: ManagedCluster
    name: uk8s-tsshared-weu-gt025-int-prod
  sourceKind: GitRepository
