apiVersion: v1
kind: Service
metadata:
  name: platform-ui
  namespace: platform-system
  labels:
    app: platform-ui
    component: service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: platform-ui
    component: ui
