apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Infrastructure
  - base/namespaces.yaml
  - base/rbac.yaml

  # GitOps Enhancements
  - flux/health-checks.yaml

  # Core Istio CRDs
  - networking/gateways.yaml
  - networking/virtual-services.yaml
  - networking/destination-rules.yaml
  - networking/service-entries.yaml
  - networking/sidecars.yaml

  # Security Enhancements
  - security/authorization-policies.yaml
  - security/peer-authentication.yaml
  - security/certificate-management.yaml
  - security/mtls-strict-enforcement.yaml

  # Applications - Multi-tenant podinfo
  - apps/tenant-a/
  - apps/tenant-b/
  - apps/shared-services/

commonLabels:
  istio.io/rev: asm-1-25
  managed-by: flux
  deployment-agent: istio-engineer

patches: []
