# Podinfo V1 - Stable version for Tenant A
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-v1
  namespace: tenant-a
  labels:
    app: podinfo
    version: v1
    deployment-agent: istio-engineer
    test-scenario: baseline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
      version: v1
  template:
    metadata:
      labels:
        app: podinfo
        version: v1
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:6.6.0
          ports:
            - containerPort: 9898
              protocol: TCP
          env:
            - name: PODINFO_UI_COLOR
              value: "#34577c" # Blue for v1
            - name: PODINFO_UI_MESSAGE
              value: "Podinfo V1 - Tenant A"
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9898
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9898
---
# Podinfo V2 - Canary version for Tenant A
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-v2
  namespace: tenant-a
  labels:
    app: podinfo
    version: v2
    deployment-agent: istio-engineer
    test-scenario: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
      version: v2
  template:
    metadata:
      labels:
        app: podinfo
        version: v2
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:6.6.1
          ports:
            - containerPort: 9898
              protocol: TCP
          env:
            - name: PODINFO_UI_COLOR
              value: "#ff6b35" # Orange for v2
            - name: PODINFO_UI_MESSAGE
              value: "Podinfo V2 CANARY - Tenant A"
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
# Podinfo V1 for Tenant B
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-v1
  namespace: tenant-b
  labels:
    app: podinfo
    version: v1
    deployment-agent: istio-engineer
    test-scenario: baseline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
      version: v1
  template:
    metadata:
      labels:
        app: podinfo
        version: v1
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:6.6.0
          ports:
            - containerPort: 9898
              protocol: TCP
          env:
            - name: PODINFO_UI_COLOR
              value: "#28a745" # Green for Tenant B
            - name: PODINFO_UI_MESSAGE
              value: "Podinfo V1 - Tenant B"
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9898
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9898
---
# Service for Tenant A
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: tenant-a
  labels:
    app: podinfo
    deployment-agent: istio-engineer
spec:
  type: ClusterIP
  ports:
    - port: 9898
      targetPort: 9898
      protocol: TCP
      name: http
    - port: 9999
      targetPort: 9999
      protocol: TCP
      name: grpc
  selector:
    app: podinfo
---
# Service for Tenant B
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: tenant-b
  labels:
    app: podinfo
    deployment-agent: istio-engineer
spec:
  type: ClusterIP
  ports:
    - port: 9898
      targetPort: 9898
      protocol: TCP
      name: http
    - port: 9999
      targetPort: 9999
      protocol: TCP
      name: grpc
  selector:
    app: podinfo
